import type { Metadata } from "next";
import { geistSans, geistMono } from "@/fonts";
import "@/app/globals.css";

import Provider from "@/services/trpc/Provider";
import { SessionProvider } from "next-auth/react";
import { Toaster } from "@/components/ui/sonner";
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Provider>
          <SessionProvider>
            <main>
              <Navbar />
              {children} <Toaster />
            </main>
          </SessionProvider>
        </Provider>
      </body>
    </html>
  );
}
