import "@/app/globals.css";
import { geistMono, geistSans } from "@/fonts";
import type { Metadata } from "next";

import { Toaster } from "@/components/ui/sonner";
import Provider from "@/services/trpc/Provider";
import { SessionProvider } from "next-auth/react";

export const metadata: Metadata = {
  title: "Biblioteka",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Provider>
          <SessionProvider>
            {children} <Toaster />
          </SessionProvider>
        </Provider>
      </body>
    </html>
  );
}
